# Generated by Django 3.2 on 2023-08-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='real_price',
        ),
    ]
