# Generated by Django 3.2 on 2023-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_orderitem_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
